name: Publish wiki
on:
  pull_request:
    branches: [master]
    paths:
      - docs/wiki/**
      - .github/workflows/on-pull.yml
permissions:
  contents: write
jobs:
  publish-wiki:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # Would be done on merge to main instead,
      # on PR here for testing.
      - name: Push wiki changes
        uses: Andrew-Chen-Wang/github-wiki-action@v4
        with:
          strategy: init
          path: docs/wiki/
          dry-run: false
