name: master
on:
  pull_request:
    branches: ["master"]

jobs:
  pushwiki:
    name: "Push Wiki"
    runs-on: ubuntu-latest
    steps:
      - name: Set up environment
        env:
          GH_AUTH_TOKEN: ${{ secrets.GH_AUTH_TOKEN }}
        run: |
          sudo apt update && sudo apt install -y build-essential; \

      - name: Checkout code
        uses: actions/checkout@v4

      - name: list wiki dir
        run: |
          cd docs/wiki
          ls
          cd architecture-stuff
          ls

      - name: Checkout wiki
        run: |
          git clone https://github.com/utilitywarehouse/swaggerui.wiki.git $GITHUB_WORKSPACE/tmp/wiki

      - name: Commit new wiki changes
        run: |
          export COMMIT_MESSAGE="new Wiki"
          cd $GITHUB_WORKSPACE/docs/wiki
          ls
          cp -r $GITHUB_WORKSPACE/tmp/wiki/.git ./
          git add .
          git commit -m "${COMMIT_MESSAGE}"
      # - name: Push new wiki changes
      #   run: |
      #     cd $GITHUB_WORKSPACE/docs/wiki && git push
